test

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,21 +1,24 @@
-echo "Select the version bump type:"
-echo "1) Major"
-echo "2) Minor"
-echo "3) Patch"
-read -p "Enter choice [1-3]: " choice
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
 
-case $choice in
-    1) 
-        npm version major -m "Bump version to %s"
-        ;;
-    2) 
-        npm version minor -m "Bump version to %s"
-        ;;
-    3) 
-        npm version patch -m "Bump version to %s"
-        ;;
-    *) 
-        echo "Invalid choice. Aborting push."
-        exit 1
-        ;;
-esac
+echo "Select the version bump type:"
+select choice in "Major" "Minor" "Patch"; do
+    case $choice in
+        Major)
+            npm version major -m "Bump version to %s"
+            break
+            ;;
+        Minor)
+            npm version minor -m "Bump version to %s"
+            break
+            ;;
+        Patch)
+            npm version patch -m "Bump version to %s"
+            break
+            ;;
+        *) 
+            echo "Invalid choice. Aborting push."
+            exit 1
+            ;;
+    esac
+done
